#!/usr/bin/env python3
"""Deterministic Hermes profile bootstrap used by Swamp Club.

The default mode is read-only and prints the complete profile contract,
including which environment variables the owner must provide. Apply mode only
creates a previously absent profile directory under HERMES_PROFILE_ROOT.

The workflow never writes secrets, installs LaunchDaemons, or starts gateways.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERMES_ROOT = Path("/Users/hermes/.hermes/profiles")
SHARED_ENV = Path("/Users/hermes/.hermes/.env")
WORKSPACES_ROOT = Path("/Users/hermes/workspaces")
HERMES_PYTHON = Path("/Users/hermes/.hermes/hermes-agent/venv/bin/python")
DEFAULT_MODEL = "openai-codex/gpt-5.6-sol-900k"
DEFAULT_WORKSPACE = WORKSPACES_ROOT
QWEN3_STT_COMMAND = (
    "/Users/hermes/.local/share/hermes-stt/.venv/bin/python "
    "/Users/hermes/.local/share/hermes-stt/qwen3_stt.py "
    "{input_path} {output_path}"
)
FALLBACK_CHAIN = [
    {"provider": "opencode-free", "model": "laguna-s-2.1-free"},
    {"provider": "opencode-free", "model": "nemotron-3.5-lightning-free"},
]

SHARED_ENV_VARS = [
    {
        "name": "LINEAR_TOKEN",
        "location": str(SHARED_ENV),
        "required": True,
        "purpose": "shared Linear MCP credential for every profile",
    },
    {
        "name": "TELEGRAM_ALLOWED_USERS",
        "location": str(SHARED_ENV),
        "required": True,
        "purpose": "default Telegram user allowlist for every profile",
    },
]
PROFILE_ENV_VARS = [
    {
        "name": "TELEGRAM_BOT_TOKEN",
        "required": True,
        "purpose": "unique BotFather token for this profile",
    },
]
OPTIONAL_PROFILE_ENV_VARS = [
    {
        "name": "LINEAR_TOKEN",
        "purpose": "optional profile override for the shared Linear MCP credential",
    },
    {
        "name": "TELEGRAM_ALLOWED_USERS",
        "purpose": "optional profile override for the shared Telegram allowlist",
    },
    {"name": "GH_TOKEN", "purpose": "scoped GitHub access when the role needs it"},
    {"name": "SWAMP_API_KEY", "purpose": "profile-scoped Swamp access when needed"},
    {"name": "XAI_API_KEY", "purpose": "xAI/Grok access when needed"},
]

BASELINE_CONFIG = """\
# Generated by swamp-ops/hermes-profile-bootstrap. Review before activation.
_config_version: 38
model:
  default: {default_model}
  provider: {provider}
{model_base_url}
fallback_providers:
{fallback_yaml}

terminal:
  backend: local
  cwd: {workspace}
  timeout: 180

stt:
  enabled: true
  language: ru
  provider: qwen3
  providers:
    qwen3:
      type: command
      command: {stt_command}
      format: txt
      timeout: 300

{role_config}
"""

LINEAR_SECRET_AND_MCP_CONFIG = """\
# Fetch LINEAR_TOKEN and TELEGRAM_ALLOWED_USERS from the default Hermes secret
# file only when the profile does not explicitly define its own value.
# Profile-specific bot/GitHub/Swamp credentials remain isolated in this .env.
secrets:
  command:
    enabled: true
    command: >-
      if ! grep -q '^LINEAR_TOKEN=' "${HERMES_HOME}/.env" 2>/dev/null;
      then grep '^LINEAR_TOKEN=' /Users/hermes/.hermes/.env; fi;
      if ! grep -q '^TELEGRAM_ALLOWED_USERS=' "${HERMES_HOME}/.env" 2>/dev/null;
      then grep '^TELEGRAM_ALLOWED_USERS=' /Users/hermes/.hermes/.env; fi
    helper_timeout_seconds: 3
    override_existing: true

mcp_servers:
  linear:
    url: https://mcp.linear.app/mcp
    headers:
      Authorization: "Bearer ${LINEAR_TOKEN}"
    prompts: false
    resources: false
"""

ROLE_CONFIGS = {
    "general": "gateway:\n  multiplex_profiles: false\n\n" + LINEAR_SECRET_AND_MCP_CONFIG,
    "broker": """\
gateway:
  multiplex_profiles: false
  platforms:
    telegram:
      enabled: false

# SIS-58 performs the production single-dispatcher cutover.
kanban:
  dispatch_in_gateway: false
""",
    "project-manager": """\
gateway:
  multiplex_profiles: false
  platforms:
    # Fail closed until the owner inserts a unique profile token and enables it.
    telegram:
      enabled: false

kanban:
  dispatch_in_gateway: false

""" + LINEAR_SECRET_AND_MCP_CONFIG,
}


def emit(payload: dict) -> None:
    print(json.dumps(payload, ensure_ascii=False, sort_keys=True))


def fail(issues: list[str], mode: str, **extra: object) -> int:
    emit({"mode": mode, "result": "error", "issues": issues, **extra})
    return 1


def env_has_key(path: Path, key: str) -> bool:
    if not path.is_file():
        return False
    for raw in path.read_text().splitlines():
        if raw.startswith(f"{key}=") and raw.split("=", 1)[1].strip():
            return True
    return False


def parse_model(value: str) -> tuple[str, str]:
    match = re.fullmatch(
        r"([a-z0-9][a-z0-9_-]{0,63})/([A-Za-z0-9][A-Za-z0-9._:/-]{0,191})",
        value,
    )
    if match is None:
        raise ValueError(f"--model must be provider/model, got '{value}'")
    return match.group(1), match.group(2)


def validate_workspace(value: str) -> Path:
    if any(ord(char) < 32 for char in value):
        raise ValueError("--workspace must not contain control characters")
    workspace = Path(value).expanduser()
    if not workspace.is_absolute():
        raise ValueError("--workspace must be an absolute path")
    workspace = workspace.resolve(strict=False)
    try:
        workspace.relative_to(WORKSPACES_ROOT.resolve(strict=False))
    except ValueError as exc:
        raise ValueError(f"--workspace must be inside {WORKSPACES_ROOT}") from exc
    return workspace


def render_config(
    provider: str,
    model: str,
    workspace: Path,
    role: str = "general",
) -> str:
    if role not in ROLE_CONFIGS:
        raise ValueError(f"unknown role '{role}'")
    fallback_yaml = "\n".join(
        f"  - provider: {item['provider']}\n    model: {item['model']}"
        for item in FALLBACK_CHAIN
    )
    model_base_url = (
        "  base_url: https://chatgpt.com/backend-api/codex"
        if provider == "openai-codex"
        else ""
    )
    return BASELINE_CONFIG.format(
        default_model=json.dumps(model),
        provider=json.dumps(provider),
        model_base_url=model_base_url,
        fallback_yaml=fallback_yaml,
        workspace=json.dumps(str(workspace)),
        stt_command=QWEN3_STT_COMMAND,
        role_config=ROLE_CONFIGS[role],
    )


def validate_yaml_text(rendered: str) -> tuple[bool, str]:
    python = HERMES_PYTHON if HERMES_PYTHON.exists() else Path(sys.executable)
    proc = subprocess.run(
        [str(python), "-c", "import sys,yaml; yaml.safe_load(sys.stdin.read())"],
        input=rendered,
        capture_output=True,
        text=True,
        timeout=30,
    )
    return proc.returncode == 0, proc.stderr.strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", required=True)
    parser.add_argument(
        "--role",
        choices=sorted(ROLE_CONFIGS),
        default="general",
        help="role-specific capability baseline",
    )
    parser.add_argument("--mode", choices=["plan", "apply"], default="plan")
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"primary provider/model (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--workspace",
        default=str(DEFAULT_WORKSPACE),
        help=f"terminal cwd under {WORKSPACES_ROOT}",
    )
    args = parser.parse_args()

    name = args.profile.strip()
    if not re.fullmatch(r"[a-z][a-z0-9-]{1,30}", name):
        return fail(
            [f"profile name '{name}' must match [a-z][a-z0-9-]{{1,30}}"],
            args.mode,
        )

    try:
        provider, default_model = parse_model(args.model)
        workspace = validate_workspace(args.workspace)
    except ValueError as exc:
        return fail([str(exc)], args.mode)

    profile_dir = HERMES_ROOT / name
    rendered = render_config(provider, default_model, workspace, role=args.role)
    yaml_ok, yaml_error = validate_yaml_text(rendered)
    if not yaml_ok:
        return fail([f"rendered config failed YAML validation: {yaml_error}"], args.mode)

    linear_enabled = args.role != "broker"
    telegram_prepared = args.role != "broker"
    shared_linear_present = env_has_key(SHARED_ENV, "LINEAR_TOKEN")
    shared_telegram_allowlist_present = env_has_key(
        SHARED_ENV, "TELEGRAM_ALLOWED_USERS"
    )
    shared_env_issues = []
    if linear_enabled and not shared_linear_present:
        shared_env_issues.append(f"LINEAR_TOKEN is missing from {SHARED_ENV}")
    if telegram_prepared and not shared_telegram_allowlist_present:
        shared_env_issues.append(
            f"TELEGRAM_ALLOWED_USERS is missing from {SHARED_ENV}"
        )
    required_shared_env = SHARED_ENV_VARS if args.role != "broker" else []
    required_profile_env = PROFILE_ENV_VARS if telegram_prepared else []
    owner_steps = [
        "authenticate the profile's model provider without copying auth files",
        "review and install the dedicated system LaunchDaemon draft",
        "start the gateway and run config, model, STT, and role-specific smoke tests",
    ]
    if telegram_prepared:
        owner_steps[:0] = [
            f"create {profile_dir / '.env'} with a unique TELEGRAM_BOT_TOKEN only when Telegram activation begins",
            "chmod 600 the profile .env",
            "enable gateway.platforms.telegram only after the unique token is present",
        ]
    planned = {
        "profile": name,
        "role": args.role,
        "profileDir": str(profile_dir),
        "configFile": str(profile_dir / "config.yaml"),
        "primaryModel": f"{default_model} (via {provider})",
        "workspace": str(workspace),
        "stt": {
            "provider": "qwen3",
            "language": "ru",
            "format": "txt",
            "timeout": 300,
        },
        "fallbackChain": [
            f"{item['model']} via {item['provider']}" for item in FALLBACK_CHAIN
        ],
        "linear": {
            "enabled": linear_enabled,
            "endpoint": "https://mcp.linear.app/mcp" if linear_enabled else None,
            "sharedTokenSource": str(SHARED_ENV) if linear_enabled else None,
            "sharedTokenPresent": shared_linear_present if linear_enabled else None,
            "profileTokenRequired": False,
            "profileOverrideSupported": linear_enabled,
        },
        "telegram": {
            "enabledAtBootstrap": False,
            "preparedForOwnerToken": telegram_prepared,
            "explicitlyDisabled": args.role in {"broker", "project-manager"},
        },
        "telegramAllowlist": {
            "sharedSource": str(SHARED_ENV) if telegram_prepared else None,
            "sharedValuePresent": (
                shared_telegram_allowlist_present if telegram_prepared else None
            ),
            "profileOverrideSupported": telegram_prepared,
            "profileValueRequired": False,
        },
        "requiredSharedEnv": required_shared_env,
        "requiredProfileEnv": required_profile_env,
        "optionalProfileEnv": OPTIONAL_PROFILE_ENV_VARS,
        "gatewaySafeWriteRoots": [str(workspace), str(profile_dir)],
        "ownerStepsBeforeActivation": owner_steps,
    }

    if args.mode == "plan":
        emit(
            {
                "mode": "plan",
                "result": "exists" if profile_dir.exists() else "would_create",
                **planned,
                "issues": shared_env_issues,
                "note": (
                    "profile already exists; nothing was modified"
                    if profile_dir.exists()
                    else "dry-run only; review variables and rerun with --mode apply"
                ),
            }
        )
        return 0

    if profile_dir.exists():
        return fail(
            ["profile directory already exists; refusing to overwrite"],
            args.mode,
            **planned,
        )
    if shared_env_issues:
        return fail(
            [f"{issue}; refusing incomplete apply" for issue in shared_env_issues],
            args.mode,
            **planned,
        )

    created = False
    try:
        profile_dir.mkdir(parents=True)
        created = True
        for subdir in ("skills", "memories", "logs", "cron"):
            (profile_dir / subdir).mkdir()
        (profile_dir / "config.yaml").write_text(rendered)
        (profile_dir / "config.yaml").chmod(0o600)
    except OSError as exc:
        if created:
            shutil.rmtree(profile_dir, ignore_errors=True)
        return fail([f"filesystem error; partial profile removed: {exc}"], args.mode)

    emit(
        {
            "mode": "apply",
            "result": "created",
            **planned,
            "issues": [],
            "nextSteps": planned["ownerStepsBeforeActivation"],
        }
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
