#!/usr/bin/env python3
"""Hermes profile bootstrap for Swamp Club.

Deterministic profile preparation: creates the profile directory structure,
writes a baseline config.yaml (model slot, ru STT, fallback chain) and
validates the result. Emits machine-readable JSON.

Modes:
  plan (default)  - read-only: report what would be created. No writes.
  apply           - create the profile directory and baseline files.

The script NEVER touches secrets (.env), LaunchDaemons, gateway processes,
or Telegram tokens. Those are consequential actions outside this workflow
and require explicit human approval.

Usage:
  python3 scripts/hermes_profile_bootstrap.py --profile <name> [--mode apply] [--model P/M]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERMES_ROOT = Path("/Users/hermes/.hermes/profiles")

FALLBACK_CHAIN = [
    {"provider": "opencode-free", "model": "laguna-s-2.1-free"},
    {"provider": "opencode-free", "model": "nemotron-3.5-lightning-free"},
]

BASELINE_CONFIG = """\
# Baseline generated by swamp-ops hermes-profile-bootstrap. Review before use.
default: {default_model}
provider: {provider}

fallback_providers:
{fallback_yaml}

stt:
  enabled: true
  language: ru

gateway:
  multiplex_profiles: false
"""


def fail(issues: list[str], mode: str) -> int:
    print(json.dumps({"mode": mode, "result": "error", "issues": issues}))
    return 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", required=True)
    ap.add_argument("--mode", choices=["plan", "apply"], default="plan")
    ap.add_argument("--model", default="nous/stealth/ox-alpha",
                    help="provider/model, e.g. openai-codex/gpt-5.6-sol")
    args = ap.parse_args()

    name = args.profile.strip()
    issues: list[str] = []
    if not re.fullmatch(r"[a-z][a-z0-9-]{1,30}", name):
        issues.append(f"profile name '{name}' must match [a-z][a-z0-9-]{{1,30}}")
        return fail(issues, args.mode)

    profile_dir = HERMES_ROOT / name
    exists = profile_dir.exists()

    if "/" in args.model:
        provider, default_model = args.model.split("/", 1)
    else:
        issues.append(f"--model must be provider/model, got '{args.model}'")
        return fail(issues, args.mode)

    fallback_yaml = "\n".join(
        f"  - provider: {e['provider']}\n    model: {e['model']}" for e in FALLBACK_CHAIN
    )
    rendered = BASELINE_CONFIG.format(
        default_model=default_model, provider=provider, fallback_yaml=fallback_yaml
    )

    planned = {
        "profile": name,
        "profileDir": str(profile_dir),
        "configFile": str(profile_dir / "config.yaml"),
        "primaryModel": f"{default_model} (via {provider})",
        "fallbackChain": [f"{e['model']} via {e['provider']}" for e in FALLBACK_CHAIN],
    }

    if args.mode == "plan":
        print(json.dumps({
            "mode": "plan",
            "result": "exists" if exists else "would_create",
            **planned,
            "issues": [],
            "note": ("profile already exists; nothing was modified"
                     if exists else "dry-run only; rerun with --mode apply"),
        }))
        return 0

    # apply
    if exists:
        print(json.dumps({
            "mode": "apply", "result": "refused_exists", **planned,
            "issues": ["profile directory already exists; refusing to overwrite"],
        }))
        return 1

    try:
        (profile_dir / "skills").mkdir(parents=True)
        (profile_dir / "memories").mkdir()
        (profile_dir / "logs").mkdir()
        (profile_dir / "cron").mkdir()
        (profile_dir / "config.yaml").write_text(rendered)
    except OSError as exc:
        return fail([f"filesystem error: {exc}"], args.mode)

    # validate written YAML (use the Hermes venv python, which ships PyYAML)
    venv_python = Path("/Users/hermes/.hermes/hermes-agent/venv/bin/python")
    validator = (
        "import sys,yaml;yaml.safe_load(open(sys.argv[1]))"
        if venv_python.exists()
        else "import json"  # unreachable fallback; keeps command well-formed
    )
    import subprocess
    proc = subprocess.run(
        [str(venv_python) if venv_python.exists() else "python3",
         "-c", validator, str(profile_dir / "config.yaml")],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return fail([f"generated config.yaml failed YAML validation: {proc.stderr.strip()}"], args.mode)

    print(json.dumps({
        "mode": "apply",
        "result": "created",
        **planned,
        "issues": [],
        "nextSteps": [
            "owner: add profile-scoped secrets to .env (chmod 600) manually",
            "owner: configure messaging platform token + allowlist",
            "owner: install system LaunchDaemon (NOT 'hermes gateway install')",
            "owner: start gateway and run Telegram smoke test",
        ],
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
